### PR TITLE
Add Custom font for Line number

### PR DESCRIPTION
**Pull request by ansh2166**
- Create `setLineNumberTypeface` to update the line number font
- Add `setLineNumberTypeface` to the documentations

### CODE REVIEW

**Review by AmrDeveloper — CHANGES_REQUESTED** [review]
Hello @ansh2166

Thanks for interesting in CodeView and your effort

Please next time create an issue first with a full description so we can start a discussion

For now, you should add documentation for this new method in 

https://github.com/AmrDeveloper/CodeView/blob/master/docs/line-number.md

Check the code review and update the line number doc, try to modify this commit

Thanks
Amr Hesham

**Comment by AmrDeveloper** [comment]
Hello @ansh2166 Any updates?

**Comment by ansh2166** [comment]
fixed

**Review by AmrDeveloper — APPROVED** [review]

**Comment by AmrDeveloper** [comment]
@ansh2166 Thank you

**Pull request merged**
